### ISSUE TITLE
Maken van .exe met cx freeze

### ISSUE THREAD

**Issue by 662781** [662781/GiraffeAI#17]
De error tekst kon ik niet kopiëren, maar dit is een screenshot ervan:
![image](https://github.com/662781/GiraffeAI/assets/70585970/8c47ae98-cd10-4b5a-ab21-7ff2f2f55074)

Dit krijg ik nadat ik:
- de cxfreeze-quickstart command gerunt heb
- gekozen heb om van GameManager.py een .exe te maken
- de nieuwe .exe probeer te runnen

Wat zou dit kunnen zijn?

**Comment by 662781** [comment]
Ik had nog nooit een setup.py gemaakt en dat zou de cxfreeze-quickstart command doen, daarom koos ik daarvoor.
De error krijg ik als de .exe run (dus of double click in de file explorer, of ./CVDojo.exe in PowerShell)

Het maken ervan kan dus wel, maar hij wilt in dit geval blijkbaar een font van ons niet laden. Geen idee waarom.

**Comment by WileyEducational** [comment]
Ik heb geprobeerd jullie project te clonen maar er ging een hoop mist met het krijgen van de gebruikte modules. Hebben jullie progressie gemaakt?

**Comment by 662781** [comment]
> Ik heb geprobeerd jullie project te clonen maar er ging een hoop mist met het krijgen van de gebruikte modules. Ik heb een hoop handmatig moeten installeren na pip install -r requirements.txt. Hebben jullie progressie gemaakt?

De requirements.txt was ook nog niet up to date, dus dat klopt. Ik heb zelf niks meer geprobeerd, had het druk met Computer Vision 2. @MartinVeltman Heb jij nog wat geprobeerd misschien?

**Comment by MartinVeltman** [comment]
Nee ik heb sinds eergister niet meer geprobeerd
